### ISSUE TITLE
Why delete the GPL-2 LICENSE file?

### ISSUE THREAD

**Issue by gbonnema** [amagnasco/xwpe#1]
Hi,

I was wondering why you deleted the LICENSE file. According to FSF the GPL license requires such a file. Of course I am not a license expert, so I ask : why delete the LICENSE file?

EDIT: I just forked the project and saw the file COPYING which contains the GPL-2 license. xD. If that is the reason, I am feeling pretty stupid (should have checked first).

**Comment by amagnasco** [comment]
Hi!

First, thank you so much for noticing that and bringing it to my attention! I saw the notification and immediately scrambled to check. You are also correct in that it is titled COPYING instead of LICENSE, so thank you for double-checking as well. Extra points for the FSF requirement.

Take care,
Alessandro
